-- =============================================================================
-- West Finance Trust: initial database schema
--
-- How the bank works (and what this schema enforces):
--   * Customers never sign themselves up. An admin registers each customer,
--     opens their accounts and assigns who can use each account.
--   * The customer's password is generated by the server and emailed to them;
--     `must_change_password` forces them to choose their own on first login.
--   * Admins post deposits and withdrawals. Customers can move money only
--     between accounts assigned to them, pay saved payees and bills.
--   * Balances never change directly: every change goes through
--     `post_transaction`, which locks the account, checks funds, writes the
--     ledger entry and the audit trail in one step.
--
-- Run once: Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
-- (Or with the CLI: `npx supabase db push`.)
-- =============================================================================

-- ---------------------------------------------------------------- 1. types

create type public.app_role as enum ('customer', 'account_opener', 'admin');
create type public.profile_status as enum ('active', 'suspended', 'closed');
create type public.account_type as enum ('checking', 'savings', 'certificate');
create type public.account_status as enum ('active', 'frozen', 'closed');
create type public.holder_relationship as enum ('primary', 'joint', 'authorized');
create type public.txn_type as enum (
  'deposit', 'withdrawal', 'transfer_in', 'transfer_out',
  'card', 'bill', 'p2p', 'interest', 'fee', 'adjustment'
);
create type public.txn_status as enum ('pending', 'posted', 'reversed', 'declined');
create type public.card_status as enum ('active', 'frozen', 'cancelled');
create type public.notice_kind as enum ('payment', 'security', 'deposit', 'info', 'blocked');
create type public.loan_product as enum ('personal', 'auto', 'home', 'business');

-- ------------------------------------------------------------- 2. profiles

-- One row per person who can sign in. `id` is the Supabase Auth user id.
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  -- the login name customers type, e.g. aloy.tony (same rules as the login form)
  user_id text not null unique
    check (user_id = lower(user_id) and user_id ~ '^[a-z0-9._-]{4,64}$'),
  first_name text not null,
  last_name text not null,
  email text not null unique,
  phone text,
  branch text not null default 'Main branch',
  role public.app_role not null default 'customer',
  status public.profile_status not null default 'active',
  must_change_password boolean not null default true,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------- 3. accounts

create sequence public.account_number_seq start 4100000001;

create table public.accounts (
  id uuid primary key default gen_random_uuid(),
  account_number text not null unique default nextval('public.account_number_seq')::text,
  type public.account_type not null,
  name text not null,                                   -- e.g. Everyday Checking
  balance numeric(14, 2) not null default 0 check (balance >= 0),
  apy numeric(5, 2) check (apy >= 0),                   -- savings and certificates
  matures_on date,                                      -- certificates only
  status public.account_status not null default 'active',
  opened_by uuid references public.profiles (id),
  opened_at timestamptz not null default now()
);

-- Who can use which account. This is how the admin "assigns" accounts:
-- one account can have several holders (joint accounts), and a person can
-- hold several accounts.
create table public.account_holders (
  account_id uuid not null references public.accounts (id) on delete cascade,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  relationship public.holder_relationship not null default 'primary',
  can_transact boolean not null default true,           -- false = view only
  assigned_by uuid references public.profiles (id),
  assigned_at timestamptz not null default now(),
  primary key (account_id, profile_id)
);
create index account_holders_profile_idx on public.account_holders (profile_id);

-- --------------------------------------------------------- 4. transactions

-- The ledger. Positive amounts are money in, negative are money out.
create table public.transactions (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.accounts (id),
  type public.txn_type not null,
  status public.txn_status not null default 'posted',
  amount numeric(14, 2) not null check (amount <> 0),
  balance_after numeric(14, 2),
  description text not null,                            -- merchant or payee shown in the app
  category text,                                        -- groceries, dining, bills ... (customer can change)
  note text check (char_length(note) <= 60),           -- customer's own note
  counterparty_account_id uuid references public.accounts (id),
  reference text not null unique
    default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12)),
  created_by uuid references public.profiles (id),      -- admin for deposits and withdrawals
  created_at timestamptz not null default now(),
  posted_at timestamptz
);
create index transactions_account_created_idx on public.transactions (account_id, created_at desc);

-- ------------------------------------------------------------------ 5. cards

-- Full card numbers and CVVs are NOT stored here. They stay with the card
-- processor (PCI DSS); the app only ever keeps the last four digits.
create table public.cards (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.accounts (id),
  holder_id uuid not null references public.profiles (id),
  last4 char(4) not null check (last4 ~ '^[0-9]{4}$'),
  expiry_month smallint not null check (expiry_month between 1 and 12),
  expiry_year smallint not null check (expiry_year >= 2024),
  status public.card_status not null default 'active',
  online_payments boolean not null default true,
  contactless boolean not null default true,
  atm_withdrawals boolean not null default true,
  use_abroad boolean not null default false,
  daily_limit numeric(10, 2) not null default 1500 check (daily_limit between 100 and 5000),
  created_at timestamptz not null default now()
);
create index cards_holder_idx on public.cards (holder_id);

-- ---------------------------------------------- 6. payees, bills and goals

-- People a customer can send money to. Added by staff, in a branch or by phone.
create table public.payees (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  bank_name text not null,
  account_mask char(4) not null,
  added_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create table public.bills (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  amount numeric(12, 2) not null check (amount > 0),
  due_day smallint not null check (due_day between 1 and 28),
  autopay boolean not null default false,
  category text not null default 'bills',
  created_at timestamptz not null default now()
);

create table public.savings_goals (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  account_id uuid not null references public.accounts (id),   -- the savings account it lives in
  name text not null check (char_length(name) between 1 and 40),
  target numeric(12, 2) not null check (target > 0),
  saved numeric(12, 2) not null default 0 check (saved >= 0),
  created_at timestamptz not null default now()
);

-- ------------------------------------- 7. notifications, settings, waitlist

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  kind public.notice_kind not null default 'info',
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index notifications_profile_idx on public.notifications (profile_id, created_at desc);

create table public.user_settings (
  profile_id uuid primary key references public.profiles (id) on delete cascade,
  card_payment_alerts boolean not null default true,
  low_balance_alerts boolean not null default true,
  login_alerts boolean not null default true,
  weekly_summary boolean not null default false,
  hide_balances boolean not null default false,
  monthly_budget numeric(12, 2) not null default 3000 check (monthly_budget > 0)
);

-- Loan waitlist: from the public website (email only) or from online banking (profile).
create table public.loan_waitlist (
  id uuid primary key default gen_random_uuid(),
  product public.loan_product not null,
  email text,
  profile_id uuid references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  check (email is not null or profile_id is not null),
  unique (product, email),
  unique (product, profile_id)
);

-- Messages from the website's contact form.
create table public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  topic text not null,
  message text not null check (char_length(message) <= 2000),
  handled_by uuid references public.profiles (id),
  handled_at timestamptz,
  created_at timestamptz not null default now()
);

-- Every staff action that matters: registrations, accounts opened, deposits, withdrawals.
create table public.audit_log (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles (id),
  action text not null,
  target_type text not null,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------ 8. helper checks

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  );
$$;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin', 'account_opener') and status = 'active'
  );
$$;

-- Admin in the app, the server using the secret key, or a direct SQL session (SQL Editor, migrations).
create or replace function public.is_privileged()
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_admin()
      or coalesce(auth.role(), '') = 'service_role'
      or session_user = 'postgres';
$$;

create or replace function public.can_view_account(p_account uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select public.is_staff() or exists (
    select 1 from public.account_holders
    where account_id = p_account and profile_id = auth.uid()
  );
$$;

create or replace function public.can_transact(p_account uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1
    from public.account_holders h
    join public.accounts a on a.id = h.account_id
    join public.profiles p on p.id = h.profile_id
    where h.account_id = p_account
      and h.profile_id = auth.uid()
      and h.can_transact
      and a.status = 'active'
      and p.status = 'active'
  );
$$;

-- ------------------------------------------------ 9. the only way money moves

-- Locks the account, checks funds, updates the balance and writes the ledger
-- row. Internal: not callable from the app directly.
create or replace function public.post_transaction(
  p_account uuid,
  p_type public.txn_type,
  p_amount numeric,
  p_description text,
  p_category text default null,
  p_note text default null,
  p_counterparty uuid default null,
  p_status public.txn_status default 'posted'
)
returns public.transactions language plpgsql security definer set search_path = '' as $$
declare
  v_balance numeric(14, 2);
  v_txn public.transactions;
begin
  select balance into v_balance
  from public.accounts
  where id = p_account and status = 'active'
  for update;

  if not found then
    raise exception 'That account doesn''t exist or isn''t active.' using errcode = 'P0002';
  end if;
  if v_balance + p_amount < 0 then
    raise exception 'Not enough money in the account.' using errcode = 'P0001';
  end if;

  update public.accounts set balance = balance + round(p_amount, 2)
  where id = p_account
  returning balance into v_balance;

  insert into public.transactions
    (account_id, type, status, amount, balance_after, description, category, note,
     counterparty_account_id, created_by, posted_at)
  values
    (p_account, p_type, p_status, round(p_amount, 2), v_balance, p_description, p_category, p_note,
     p_counterparty, auth.uid(), case when p_status = 'posted' then now() end)
  returning * into v_txn;

  return v_txn;
end;
$$;

-- Tell every holder of the account about money arriving or leaving.
create or replace function public.notify_account_holders()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.type in ('transfer_in', 'transfer_out') then
    return new; -- the customer made these themselves
  end if;
  insert into public.notifications (profile_id, kind, title, body)
  select h.profile_id,
         case when new.amount > 0 then 'deposit'::public.notice_kind else 'payment'::public.notice_kind end,
         case new.type
           when 'deposit' then 'Deposit received'
           when 'withdrawal' then 'Withdrawal made'
           when 'bill' then 'Bill paid'
           when 'p2p' then 'Payment sent'
           when 'interest' then 'Interest paid'
           else 'Account activity'
         end,
         format('%s %s. %s', to_char(abs(new.amount), 'FM$999,999,990.00'),
                case when new.amount > 0 then 'in' else 'out' end, new.description)
  from public.account_holders h
  where h.account_id = new.account_id;
  return new;
end;
$$;

create trigger transactions_notify
after insert on public.transactions
for each row execute function public.notify_account_holders();

-- ------------------------------------------- 10. admin: deposits, withdrawals

create or replace function public.admin_deposit(
  p_account uuid,
  p_amount numeric,
  p_description text default 'Cash deposit at branch'
)
returns public.transactions language plpgsql security definer set search_path = '' as $$
declare v_txn public.transactions;
begin
  if not public.is_privileged() then
    raise exception 'Only an admin can post deposits.' using errcode = '42501';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'The deposit amount must be above zero.' using errcode = '22023';
  end if;

  v_txn := public.post_transaction(p_account, 'deposit', p_amount, p_description, 'income');

  insert into public.audit_log (actor_id, action, target_type, target_id, details)
  values (auth.uid(), 'deposit', 'account', p_account,
          jsonb_build_object('amount', round(p_amount, 2), 'transaction_id', v_txn.id, 'description', p_description));
  return v_txn;
end;
$$;

create or replace function public.admin_withdrawal(
  p_account uuid,
  p_amount numeric,
  p_description text default 'Cash withdrawal at branch'
)
returns public.transactions language plpgsql security definer set search_path = '' as $$
declare v_txn public.transactions;
begin
  if not public.is_privileged() then
    raise exception 'Only an admin can post withdrawals.' using errcode = '42501';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'The withdrawal amount must be above zero.' using errcode = '22023';
  end if;

  v_txn := public.post_transaction(p_account, 'withdrawal', -p_amount, p_description, 'other');

  insert into public.audit_log (actor_id, action, target_type, target_id, details)
  values (auth.uid(), 'withdrawal', 'account', p_account,
          jsonb_build_object('amount', round(p_amount, 2), 'transaction_id', v_txn.id, 'description', p_description));
  return v_txn;
end;
$$;

-- Opens an account for a registered customer and assigns it to them.
create or replace function public.admin_open_account(
  p_profile uuid,
  p_type public.account_type,
  p_name text default null,
  p_apy numeric default null,
  p_matures_on date default null,
  p_opening_deposit numeric default 0
)
returns public.accounts language plpgsql security definer set search_path = '' as $$
declare v_account public.accounts;
begin
  if not (public.is_staff() or public.is_privileged()) then
    raise exception 'Only staff can open accounts.' using errcode = '42501';
  end if;

  insert into public.accounts (type, name, apy, matures_on, opened_by)
  values (
    p_type,
    coalesce(p_name, case p_type
      when 'checking' then 'Everyday Checking'
      when 'savings' then 'High-Yield Savings'
      else '12-month Certificate' end),
    p_apy,
    p_matures_on,
    auth.uid()
  )
  returning * into v_account;

  insert into public.account_holders (account_id, profile_id, relationship, assigned_by)
  values (v_account.id, p_profile, 'primary', auth.uid());

  insert into public.audit_log (actor_id, action, target_type, target_id, details)
  values (auth.uid(), 'open_account', 'account', v_account.id,
          jsonb_build_object('profile_id', p_profile, 'type', p_type));

  if coalesce(p_opening_deposit, 0) > 0 then
    perform public.admin_deposit(v_account.id, p_opening_deposit, 'Opening deposit');
    select * into v_account from public.accounts where id = v_account.id;
  end if;

  return v_account;
end;
$$;

-- ------------------------------------------ 11. customer money movements

-- Between two accounts the customer holds.
create or replace function public.transfer_between_accounts(
  p_from uuid,
  p_to uuid,
  p_amount numeric,
  p_note text default null
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  v_from_name text;
  v_to_name text;
  v_out public.transactions;
begin
  if p_from = p_to then
    raise exception 'Choose two different accounts.' using errcode = '22023';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'Enter an amount above zero.' using errcode = '22023';
  end if;
  if not public.can_transact(p_from) or not public.can_transact(p_to) then
    raise exception 'You can only move money between your own accounts.' using errcode = '42501';
  end if;

  -- lock both rows in a fixed order so two transfers can't deadlock
  perform 1 from public.accounts where id in (p_from, p_to) order by id for update;
  select name into v_from_name from public.accounts where id = p_from;
  select name into v_to_name from public.accounts where id = p_to;

  v_out := public.post_transaction(p_from, 'transfer_out', -p_amount, 'To ' || v_to_name, 'transfer', p_note, p_to);
  perform public.post_transaction(p_to, 'transfer_in', p_amount, 'From ' || v_from_name, 'transfer', p_note, p_from);
  return v_out.id;
end;
$$;

-- To a saved payee. Stays pending until the payment network confirms it.
create or replace function public.send_to_payee(
  p_from uuid,
  p_payee uuid,
  p_amount numeric,
  p_note text default null
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  v_payee public.payees;
  v_txn public.transactions;
begin
  select * into v_payee from public.payees where id = p_payee and owner_id = auth.uid();
  if not found then
    raise exception 'That payee isn''t on your list.' using errcode = '42501';
  end if;
  if not public.can_transact(p_from) then
    raise exception 'You can''t send money from that account.' using errcode = '42501';
  end if;
  if p_amount is null or p_amount <= 0 or p_amount > 25000 then
    raise exception 'Enter an amount between $0.01 and $25,000.' using errcode = '22023';
  end if;

  v_txn := public.post_transaction(p_from, 'p2p', -p_amount, v_payee.name, 'p2p', p_note, null, 'pending');
  return v_txn.id;
end;
$$;

create or replace function public.pay_bill(p_from uuid, p_bill uuid)
returns uuid language plpgsql security definer set search_path = '' as $$
declare
  v_bill public.bills;
  v_txn public.transactions;
begin
  select * into v_bill from public.bills where id = p_bill and owner_id = auth.uid();
  if not found then
    raise exception 'That bill isn''t on your list.' using errcode = '42501';
  end if;
  if not public.can_transact(p_from) then
    raise exception 'You can''t pay bills from that account.' using errcode = '42501';
  end if;

  v_txn := public.post_transaction(p_from, 'bill', -v_bill.amount, v_bill.name, v_bill.category);
  return v_txn.id;
end;
$$;

-- Moves money into the goal's savings account and counts it towards the goal.
create or replace function public.add_to_goal(p_goal uuid, p_from uuid, p_amount numeric)
returns public.savings_goals language plpgsql security definer set search_path = '' as $$
declare v_goal public.savings_goals;
begin
  select * into v_goal from public.savings_goals where id = p_goal and owner_id = auth.uid() for update;
  if not found then
    raise exception 'That goal isn''t yours.' using errcode = '42501';
  end if;

  perform public.transfer_between_accounts(p_from, v_goal.account_id, p_amount, v_goal.name);

  update public.savings_goals set saved = saved + round(p_amount, 2)
  where id = p_goal
  returning * into v_goal;
  return v_goal;
end;
$$;

-- ------------------------------------------------ 12. automatic defaults

create or replace function public.create_default_settings()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.user_settings (profile_id) values (new.id) on conflict do nothing;
  return new;
end;
$$;

create trigger profiles_default_settings
after insert on public.profiles
for each row execute function public.create_default_settings();

-- ------------------------------------------------ 13. row level security

alter table public.profiles enable row level security;
alter table public.accounts enable row level security;
alter table public.account_holders enable row level security;
alter table public.transactions enable row level security;
alter table public.cards enable row level security;
alter table public.payees enable row level security;
alter table public.bills enable row level security;
alter table public.savings_goals enable row level security;
alter table public.notifications enable row level security;
alter table public.user_settings enable row level security;
alter table public.loan_waitlist enable row level security;
alter table public.contact_messages enable row level security;
alter table public.audit_log enable row level security;

-- Customers see themselves; staff see everyone. Customers can't edit their
-- details online (changes are verified in person), so there is no update policy.
create policy "profiles: read own, staff read all" on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_staff());

create policy "accounts: holders and staff" on public.accounts
  for select to authenticated using (public.can_view_account(id));

create policy "account_holders: own rows, staff all" on public.account_holders
  for select to authenticated using (profile_id = auth.uid() or public.is_staff());

create policy "transactions: accounts you can see" on public.transactions
  for select to authenticated using (public.can_view_account(account_id));

-- Customers may add a note or change the category, nothing else (see column grants below).
create policy "transactions: holders edit note and category" on public.transactions
  for update to authenticated
  using (public.can_view_account(account_id))
  with check (public.can_view_account(account_id));

create policy "cards: holder and staff" on public.cards
  for select to authenticated using (holder_id = auth.uid() or public.is_staff());

-- Holders can freeze/unfreeze and change controls, but never revive a cancelled card.
create policy "cards: holder changes controls" on public.cards
  for update to authenticated
  using (holder_id = auth.uid() and status <> 'cancelled')
  with check (holder_id = auth.uid() and status in ('active', 'frozen'));

create policy "payees: own, staff all" on public.payees
  for select to authenticated using (owner_id = auth.uid() or public.is_staff());

create policy "bills: own" on public.bills
  for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy "goals: read own" on public.savings_goals
  for select to authenticated using (owner_id = auth.uid());
create policy "goals: create own" on public.savings_goals
  for insert to authenticated
  with check (owner_id = auth.uid() and public.can_view_account(account_id) and saved = 0);
create policy "goals: edit own" on public.savings_goals
  for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "goals: delete own" on public.savings_goals
  for delete to authenticated using (owner_id = auth.uid());

create policy "notifications: own" on public.notifications
  for select to authenticated using (profile_id = auth.uid());
create policy "notifications: mark own read" on public.notifications
  for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());

create policy "settings: own" on public.user_settings
  for select to authenticated using (profile_id = auth.uid());
create policy "settings: update own" on public.user_settings
  for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());

create policy "waitlist: own entries" on public.loan_waitlist
  for select to authenticated using (profile_id = auth.uid());
create policy "waitlist: join as yourself" on public.loan_waitlist
  for insert to authenticated with check (profile_id = auth.uid() and email is null);

create policy "contact messages: staff read" on public.contact_messages
  for select to authenticated using (public.is_staff());
create policy "contact messages: staff mark handled" on public.contact_messages
  for update to authenticated using (public.is_staff()) with check (public.is_staff());

create policy "audit log: admins read" on public.audit_log
  for select to authenticated using (public.is_admin());

-- ------------------------------------------------------ 14. privileges

-- Nothing is readable without signing in. (The website's forms write through
-- the server with the secret key, which bypasses RLS.)
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

-- Signed-in users can only write the columns the policies above expect.
revoke insert, update, delete on
  public.profiles, public.accounts, public.account_holders, public.transactions,
  public.cards, public.payees, public.notifications, public.user_settings,
  public.audit_log, public.contact_messages
from authenticated;

grant update (note, category) on public.transactions to authenticated;
grant update (status, online_payments, contactless, atm_withdrawals, use_abroad, daily_limit)
  on public.cards to authenticated;
grant update (read_at) on public.notifications to authenticated;
grant update (card_payment_alerts, low_balance_alerts, login_alerts, weekly_summary, hide_balances, monthly_budget)
  on public.user_settings to authenticated;
grant update (handled_by, handled_at) on public.contact_messages to authenticated;
-- Goals: rename or change the target only. `saved` moves solely through add_to_goal().
revoke update on public.savings_goals from authenticated;
grant update (name, target) on public.savings_goals to authenticated;

-- Functions: internal helpers are locked away; the app calls the rest via RPC.
revoke execute on all functions in schema public from public, anon;
revoke execute on function public.post_transaction(uuid, public.txn_type, numeric, text, text, text, uuid, public.txn_status)
  from authenticated;
revoke execute on function public.notify_account_holders() from authenticated;
revoke execute on function public.create_default_settings() from authenticated;

grant execute on function
  public.is_admin(),
  public.is_staff(),
  public.can_view_account(uuid),
  public.can_transact(uuid),
  public.admin_deposit(uuid, numeric, text),
  public.admin_withdrawal(uuid, numeric, text),
  public.admin_open_account(uuid, public.account_type, text, numeric, date, numeric),
  public.transfer_between_accounts(uuid, uuid, numeric, text),
  public.send_to_payee(uuid, uuid, numeric, text),
  public.pay_bill(uuid, uuid),
  public.add_to_goal(uuid, uuid, numeric)
to authenticated, service_role;

-- ------------------------------------------------------ 15. live updates

-- Lets the dashboard update instantly when a deposit or payment lands.
-- (Realtime respects the row level security above.)
alter publication supabase_realtime add table public.transactions, public.notifications, public.accounts;
